spring.application.name=ingestor

spring.rabbitmq.host=${MESSAGE_BROKER_HOST:localhost}
spring.rabbitmq.port=${MESSAGE_BROKER_PORT:5672}
spring.rabbitmq.username=${MESSAGE_BROKER_USERNAME:guest}
spring.rabbitmq.password=${MESSAGE_BROKER_PASSWORD:guest}