spring.application.name=ingestor

spring.rabbitmq.host=${MESSAGE_BROKER_HOST}
spring.rabbitmq.port=${MESSAGE_BROKER_PORT}
spring.rabbitmq.username=${MESSAGE_BROKER_USERNAME}
spring.rabbitmq.password=${MESSAGE_BROKER_PASSWORD}