spring.application.name=ingestor

spring.rabbitmq.host=${MESSAGE_BROKER_HOST:localhost}
spring.rabbitmq.port=${MESSAGE_BROKER_PORT:5672}
spring.rabbitmq.username=${MESSAGE_BROKER_USERNAME:guest}
spring.rabbitmq.password=${MESSAGE_BROKER_PASSWORD:guest}

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/loyalty_ledger}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver